apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs
        image: arthurescriou/redis-node:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: "redis://redis-master:6379"
        - name: REDIS_REPLICAS_URL
          value: "redis://redis-replica.default.svc.cluster.local:6379"
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
